### ISSUE TITLE
Develop Club Information Page for the Registration Packet

### ISSUE THREAD

**Issue by BSchoolland** [Community-ALI/club-website#15]
#### Description
Use the components created in issue #14 to design the club information page
![image](https://github.com/Community-ALI/club-website/assets/95189424/ec62dd59-438e-4df8-8364-9934d42c0506)

#### Tasks
- [x] Create the page
- [x] Test that all the components work well on any screen size
- [x] Link the page from the landing page
