### ISSUE TITLE
Develop Members Page

### ISSUE THREAD

**Issue by BSchoolland** [Community-ALI/club-website#18]
### Description 
A page where you can add and remove members.  Will autofill later, but does not have to now.

#### Tasks 
- [ ] Design the page
- [ ] Create JavaScript for adding and removing members
- [ ] Test the page
