### ISSUE TITLE
Develop Agreement Page

### ISSUE THREAD

**Issue by BSchoolland** [Community-ALI/club-website#19]
### Description
The agreement page, having signature boxes and a wall of text.
![image](https://github.com/Community-ALI/club-website/assets/95189424/e1de908b-b5d4-4262-9dd5-8135472e856a)

#### Tasks 
- [ ] Design the page
- [ ] Add the text and such
- [ ] Figure out how to add an e-signature box
