### ISSUE TITLE
Initialize Basic Page Structure in Next.js App

### ISSUE THREAD

**Issue by BSchoolland** [Community-ALI/club-website#2]
#### description
To create a page in a Next.JS application, add a folder to the app folder, and then put a page.js file in that folder.  When you navigate to /your-folder-name, the page will show up.  

Folder structure should look something like this:
app/
|--- page.js (the landing page)
|--- create-account (folder for a page)
|     |--- page.js (the react component for the page)
|--- sign-in
|     |--- page.js
|--- contacts
|     |--- page.js
... and so on

I am not smarter than Adrean. Adrean is the best (Ben said this btw)

#### tasks
- [x] add a folder for each page detailed in the figma design (other than landing page which goes directly in app)
- [x] add a page.js that returns a component that is just an h1 with the name of that page
- [x] test that navigating to different pages works using their urls
