### ISSUE TITLE
Club Constitution 

### ISSUE THREAD

**Issue by BSchoolland** [Community-ALI/club-website#20]
### Description
Design the Club Constitution page, and add a way to upload files.

![image](https://github.com/Community-ALI/club-website/assets/95189424/6fab0f1e-0e07-4053-84ec-ab2969b2916d)

#### Tasks
- [ ] Design the page
- [ ] Add the file upload button
- [ ] Add a way to preview files
