### ISSUE TITLE
Develop Submit Page

### ISSUE THREAD

**Issue by BSchoolland** [Community-ALI/club-website#21]
### Description
Add the submit page frontend.  It can be filled with default values for now
![image](https://github.com/Community-ALI/club-website/assets/95189424/486bf61a-0eb9-4de9-a81d-f7bc5261b19a)

#### Tasks
- [ ] Make the page
- [ ] Fill with default information
- [ ] Make it easy to connect to javascript
