### ISSUE TITLE
Backend: Develop API Structure

### ISSUE THREAD

**Issue by BSchoolland** [Community-ALI/club-website#22]
### Description

Add a folder and route.js file for each needed API, and an empty function for each needed API call.

Tasks represents different backend related actions needed, each of these should 
#### Tasks
- [x] Sign in
- [x] Create Account
- [x] Change Password
- [x] Create/ update form draft
- [x] Get form draft
- [x] Submit form (email and save to database)
