### ISSUE TITLE
Backend: Connect to an SQL Database

### ISSUE THREAD

**Issue by BSchoolland** [Community-ALI/club-website#23]
### Description
Create and test a db.js module to be used by other files to perform queries.  

#### Tasks
- [x] Identify a good database service
- [x] Create and connect to the database
- [x] Create tables for each type of data we want to store
- [x] Test the database by reading and writing with a test API
