### ISSUE TITLE
Backend: Implement the Account API

### ISSUE THREAD

**Issue by BSchoolland** [Community-ALI/club-website#24]
### Description
Add functionality which allows users to create and log in to accounts.  Accounts should include all the required fields.

#### Tasks
- [x] Connect the API to the frontend
- [x] Code account creation
- [x] Code login 
- [x] Test account creation and login
- [x] Code logout 
- [x] Test logout
