### ISSUE TITLE
Implement Header

### ISSUE THREAD

**Issue by BSchoolland** [Community-ALI/club-website#5]
#### Description
Add the header as a component.
![image](https://github.com/Community-ALI/club-website/assets/95189424/a34faaf0-7202-4cf8-8ef4-843e9a7597cf)

#### tasks
- [x] Research how components should be added in Next.js
- [x] Add a react component for the header 
- [x] Test the react component by importing it into the landing page
