### ISSUE TITLE
IP recognition system for unlogged in users

### ISSUE THREAD

**Issue by BSchoolland** [Community-ALI/club-website#58]
### Description
A system that stores unsaved drafts to the user's ip address, allowing them to access them later.  This can be done after the 10th.
### Tasks:
- [ ] Another table in the database for these types of drafts 
- [ ] API calls for accountless users that use the IP instead of an account
- [ ] ability to transfer data from IP to account when a user creates an account.
