### ISSUE TITLE
Draft API

### ISSUE THREAD

**Issue by BSchoolland** [Community-ALI/club-website#60]
Create an api to handle saving and loading drafts

### Tasks
- [x] set up api routes
- [x] #70
- [x] database table creation
- [x] Post route
- [x] get route
- [x] handle the case where there is no draft yet.
- [x] Handle cases where the user is not logged in.
