### ISSUE TITLE
Develop application submission

### ISSUE THREAD

**Issue by BSchoolland** [Community-ALI/club-website#61]
On submit, the website stores the data, then sends a pdf to the admin's email.  
### Tasks:
- [x] Develop frontend form submission
- [x] Develop layout of api routes
- [x] Implement API calls
- [x] Create a database table/ model for submitted applications
- [x] Integrate PDF generation see #26 
- [x] Send email 
- [x] Send email with attached PDF
