### ISSUE TITLE
Implement Spanish Mode

### ISSUE THREAD

**Issue by BSchoolland** [Community-ALI/club-website#8]
#### Description

Create an English/ Spanish toggle on the navbar/ header, and have that decide whether to display the site in English or Spanish.  

![image](https://github.com/Community-ALI/club-website/assets/95189424/69aad639-6aa1-4159-acc9-504355c03197)

#### Tasks
- [ ] Add the button visually
- [ ] Save the state based on the user's account and/ or ip address
- [ ] Have the button switch text to Spanish or English across the site
- [ ] Test that the formatting all looks correct in Spanish mode (since the site may not initially be designed to look good with slightly different numbers of characters)
