### ISSUE TITLE
 Design Sign in component

### ISSUE THREAD

**Issue by BSchoolland** [Community-ALI/club-website#9]
#### Description
Add the sign in component, without actual functionality.
![image](https://github.com/Community-ALI/club-website/assets/95189424/a36ba99d-75b1-45a5-b196-93ef9a9e4096)

### tasks:
- [x] Add the component
- [x] Connect the component using the navbar/ header
- [x] Test that switching between components works
